## Project
name: marketing_leads_pilot
version: "1.0"
config-version: 2
profile: marketing_leads_pilot

## Sources
model-paths: [models]
seed-paths: [seeds]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  marketing_leads_pilot:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    business_ready:
      +materialized: table
