tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: sysadmin
      database: nra_demo_db
      schema: dbt_projects
      warehouse: nra_default_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: sysadmin
      database: nra_demo_db
      schema: dbt_projects_prod
      warehouse: nra_default_wh